import StyleDictionary from 'style-dictionary';
import { readFileSync, writeFileSync } from 'node:fs';

// Read a resolved token's value/type/description regardless of whether Style
// Dictionary exposes DTCG ($-prefixed) or legacy keys.
const valueOf = (token) => token.value ?? token.$value;
const typeOf = (token) => token.$type ?? token.type ?? token.original?.$type;
const descriptionOf = (token) => token.$description ?? token.description ?? token.original?.$description ?? '';

// Format a resolved token value into a CSS-ready string per its DTCG $type.
function cssValue(token) {
  const type = typeOf(token);
  const value = valueOf(token);
  switch (type) {
    case 'fontFamily':
      return (Array.isArray(value) ? value : [value])
        .map((family) => (/\s/.test(family) ? `"${family}"` : family))
        .join(', ');
    case 'cubicBezier':
      return `cubic-bezier(${value.join(', ')})`;
    case 'shadow': {
      const list = Array.isArray(value) ? value : [value];
      return list
        .map((s) => `${s.offsetX} ${s.offsetY} ${s.blur} ${s.spread} ${s.color}`)
        .join(', ');
    }
    default:
      return String(value);
  }
}

// Machine-readable catalogue the design site renders from. One entry per token.
StyleDictionary.registerFormat({
  name: 'notekit/json',
  format: ({ dictionary }) => {
    const tokens = dictionary.allTokens.map((token) => ({
      name: `--nk-${token.path.join('-')}`,
      path: token.path,
      category: token.path[0],
      group: token.path[1] ?? null,
      type: typeOf(token),
      value: cssValue(token),
      raw: valueOf(token),
      description: descriptionOf(token),
    }));
    return JSON.stringify({ tokens }, null, 2) + '\n';
  },
});

// Flat CSS custom properties under :root — the canonical names (--nk-*).
StyleDictionary.registerFormat({
  name: 'notekit/css-vars',
  format: ({ dictionary }) => {
    const lines = dictionary.allTokens.map(
      (token) => `  --nk-${token.path.join('-')}: ${cssValue(token)};`,
    );
    return `:root {\n${lines.join('\n')}\n}\n`;
  },
});

// Core-shaped output: emits packages/core's own variable names so @notekit/core
// can consume the token package via aliases (Stage 2 migration) with zero
// visual diff. This is the concrete "alias, not big-bang rename" artifact.
StyleDictionary.registerFormat({
  name: 'notekit/core-css',
  format: ({ dictionary }) => {
    const byPath = new Map(dictionary.allTokens.map((t) => [t.path.join('.'), t]));
    const v = (path) => cssValue(byPath.get(path));

    const themeBlock = (theme) => {
      const keys = dictionary.allTokens
        .filter((t) => t.path[0] === 'color' && t.path[1] === theme)
        .map((t) => `  --${t.path.slice(2).join('-')}: ${cssValue(t)};`);
      return `[data-theme="${theme}"] {\n${keys.join('\n')}\n  color-scheme: ${theme};\n}`;
    };

    const scale = [
      '.nk {',
      '  --nk-accent: var(--accent);',
      '  --nk-accent-contrast: var(--primary-foreground);',
      '  --nk-accent-soft: var(--accent-soft);',
      `  --ui-font: ${v('font.family.ui')};`,
      `  --editor-font: ${v('font.family.editor')};`,
      `  --mono-font: ${v('font.family.mono')};`,
      `  --ui-size: ${v('font.size.ui')};`,
      `  --editor-size: ${v('font.size.editor')};`,
      `  --editor-leading: ${v('font.leading.editor')};`,
      `  --measure: ${v('font.measure')};`,
      `  --r-sm: ${v('radius.sm')};`,
      `  --r-md: ${v('radius.md')};`,
      `  --r-lg: ${v('radius.lg')};`,
      `  --gap-1: ${v('space.1')};`,
      `  --gap-2: ${v('space.2')};`,
      `  --gap-3: ${v('space.3')};`,
      `  --gap-4: ${v('space.4')};`,
      `  --gap-5: ${v('space.5')};`,
      `  --gap-6: ${v('space.6')};`,
      '}',
    ].join('\n');

    return [
      '/* Generated by @notekit/tokens — do not edit by hand. */',
      themeBlock('dark'),
      themeBlock('light'),
      scale,
      '',
    ].join('\n\n');
  },
});

// Backoffice-shaped output: reproduces apps/backoffice's Tailwind v4 @theme block
// (shadcn neutral palette) exactly, so the backoffice can source its values here.
StyleDictionary.registerFormat({
  name: 'notekit/backoffice-css',
  format: ({ dictionary }) => {
    const varsFor = (mode) =>
      dictionary.allTokens
        .filter((t) => t.path[0] === 'color' && t.path[1] === 'backoffice' && t.path[2] === mode)
        .map((t) => `    --color-${t.path.slice(3).join('-')}: ${cssValue(t)};`);

    const radius = [
      '',
      '  --radius: 0.5rem;',
      '  --radius-sm: calc(var(--radius) - 4px);',
      '  --radius-md: calc(var(--radius) - 2px);',
      '  --radius-lg: var(--radius);',
      '  --radius-xl: calc(var(--radius) + 4px);',
    ];

    return [
      '/* Generated by @notekit/tokens — do not edit by hand. */',
      `@theme {\n${varsFor('light').map((line) => line.slice(2)).join('\n')}\n${radius.join('\n')}\n}`,
      `@layer base {\n  .dark {\n${varsFor('dark').join('\n')}\n  }\n}`,
      '',
    ].join('\n\n');
  },
});

const sd = new StyleDictionary({
  source: ['src/*.tokens.json'],
  usesDtcg: true,
  platforms: {
    json: {
      transforms: ['name/kebab'],
      buildPath: 'dist/',
      files: [{ destination: 'tokens.json', format: 'notekit/json' }],
    },
    css: {
      transforms: ['name/kebab'],
      buildPath: 'dist/css/',
      files: [
        { destination: 'variables.css', format: 'notekit/css-vars' },
        { destination: 'core.css', format: 'notekit/core-css' },
        { destination: 'backoffice.css', format: 'notekit/backoffice-css' },
      ],
    },
  },
});

await sd.buildAllPlatforms();

// Landing-shaped output: apps/landing's full :root, centralized verbatim (order
// preserved, incl. intentional duplicate keys). Mostly marketing-specific machinery
// (layers, easings, page padding, masks), so it is captured as an ordered var list
// rather than modeled as DTCG design tokens.
const landingVars = JSON.parse(readFileSync(new URL('./src/landing.vars.json', import.meta.url)));
const landingCss =
  '/* Generated by @notekit/tokens — do not edit by hand. */\n:root {\n' +
  landingVars.map(({ name, value }) => `  ${name}: ${value};`).join('\n') +
  '\n}\n';
writeFileSync(new URL('./dist/css/landing.css', import.meta.url), landingCss);

console.log(
  '@notekit/tokens: built dist/tokens.json, dist/css/variables.css, core.css, backoffice.css, landing.css',
);
