export interface FAQItem {
  question: string
  answer: string
}

export interface FAQCategory {
  id: string
  title: string
  items: FAQItem[]
}

export const landingFAQs: FAQItem[] = [
  {
    question: "What is ScaleX in one sentence?",
    answer:
      "ScaleX is an AI-agent-native decentralized exchange that integrates trading, prediction markets, and lending to maximize your capital efficiency.",
  },
  {
    question: "What differentiates ScaleX from other exchanges?",
    answer:
      "Unlike traditional exchanges, ScaleX enables you to simultaneously earn yield from your trading and betting activities.",
  },
  {
    question: "Where does the yield come from?",
    answer:
      "The yield is generated by automatically routing your idle margin and collateral into underlying lending protocols.",
  },
  {
    question: "How flexible is the ScaleX agent?",
    answer:
      "ScaleX agents are highly flexible—you can easily customize your own trading policies or subscribe to strategies created by other users.",
  },
  {
    question: "What are sxTokens?",
    answer:
      "sxTokens are yield-bearing receipt tokens you receive when depositing assets into ScaleX. They represent your deposit plus accrued interest, and can be used as collateral for trading, effectively letting your money work in two places at once.",
  },
  {
    question: "What is ERC-8004?",
    answer:
      "ERC-8004 is a token standard co-authored by ScaleX that provides on-chain identity for AI agents. It enables agents to have verifiable credentials, reputation scores, and permissioned access to DeFi protocols in a trustless manner.",
  },
  {
    question: "How do AI agents interact with ScaleX?",
    answer:
      "AI agents can interact with ScaleX through MCP (Model Context Protocol) integration and dedicated agent SDKs. They can execute trades, manage lending positions, and participate in prediction markets autonomously with their own on-chain identity via ERC-8004.",
  },
  {
    question: "How does ScaleX ensure security?",
    answer:
      "ScaleX employs multiple security layers including audited smart contracts, Chainlink oracle integration for tamper-proof price feeds, isolated risk pools for lending markets, and the X402 protocol for secure agent-to-protocol payments.",
  },
]

export const faqCategories: FAQCategory[] = [
  {
    id: "general",
    title: "General",
    items: [
      {
        question: "What is ScaleX in one sentence?",
        answer:
          "ScaleX is an AI-agent-native decentralized exchange that integrates trading, prediction markets, and lending to maximize your capital efficiency.",
      },
      {
        question: "What is ScaleX Protocol?",
        answer:
          "ScaleX is an AI-agent-native decentralized exchange (DEX) with integrated lending, prediction markets, and ERC-8004 agent identity. It's designed to be the most capital-efficient and safe DApp for both AI agents and human users.",
      },
      {
        question: "What differentiates ScaleX from other exchanges?",
        answer:
          "Unlike traditional exchanges, ScaleX enables you to simultaneously earn yield from your trading and betting activities.",
      },
      {
        question: "Who is ScaleX built for?",
        answer:
          "ScaleX is built for both human traders and AI agents. Whether you're a DeFi power user looking for capital efficiency, a developer building autonomous trading agents, or a newcomer exploring decentralized finance, ScaleX provides the tools and infrastructure you need.",
      },
      {
        question: "How is ScaleX different from other DEXs?",
        answer:
          "Unlike traditional DEXs where idle capital earns nothing, ScaleX integrates lending directly into the trading flow. Your margin and collateral automatically earn yield. Combined with AI-agent-native design and ERC-8004 identity, ScaleX is purpose-built for the future of autonomous finance.",
      },
    ],
  },
  {
    id: "trading",
    title: "Trading",
    items: [
      {
        question: "What types of trading does ScaleX support?",
        answer:
          "ScaleX supports spot trading, perpetual futures, and prediction markets. All trading types benefit from the integrated lending layer, meaning your collateral earns yield while you trade.",
      },
      {
        question: "How do limit orders earn yield?",
        answer:
          "When you place a limit order on ScaleX, the capital backing that order is automatically deposited into lending pools. You earn interest until the order is filled, eliminating the opportunity cost of waiting for price targets.",
      },
      {
        question: "What are prediction markets on ScaleX?",
        answer:
          "ScaleX's prediction markets allow users and AI agents to trade on the outcomes of real-world events. Positions are tokenized and can be traded on secondary markets, with settlement powered by Chainlink oracles for reliable resolution.",
      },
    ],
  },
  {
    id: "lending-yield",
    title: "Lending & Yield",
    items: [
      {
        question: "Where does the yield come from?",
        answer:
          "The yield is generated by automatically routing your idle margin and collateral into underlying lending protocols.",
      },
      {
        question: "How does the yield mechanism work?",
        answer:
          "ScaleX automatically routes idle margin and collateral into lending pools, so your capital earns yield even while waiting for trades to execute. This eliminates the opportunity cost of capital sitting idle in limit orders.",
      },
      {
        question: "What are sxTokens?",
        answer:
          "sxTokens are yield-bearing receipt tokens you receive when depositing assets into ScaleX. They represent your deposit plus accrued interest, and can be used as collateral for trading, effectively letting your money work in two places at once.",
      },
      {
        question: "What determines the lending APY?",
        answer:
          "Lending APY is determined by supply and demand dynamics within each lending pool. Higher utilization rates lead to higher yields for lenders. Rates are calculated algorithmically and update in real-time based on market conditions.",
      },
    ],
  },
  {
    id: "ai-agents",
    title: "AI Agents",
    items: [
      {
        question: "How flexible is the ScaleX agent?",
        answer:
          "ScaleX agents are highly flexible—you can easily customize your own trading policies or subscribe to strategies created by other users.",
      },
      {
        question: "How do AI agents interact with ScaleX?",
        answer:
          "AI agents can interact with ScaleX through MCP (Model Context Protocol) integration and dedicated agent SDKs. They can execute trades, manage lending positions, and participate in prediction markets autonomously with their own on-chain identity via ERC-8004.",
      },
      {
        question: "What is ERC-8004?",
        answer:
          "ERC-8004 is a token standard co-authored by ScaleX that provides on-chain identity for AI agents. It enables agents to have verifiable credentials, reputation scores, and permissioned access to DeFi protocols in a trustless manner.",
      },
      {
        question: "Can I build my own trading agent?",
        answer:
          "Yes! ScaleX provides comprehensive SDKs, API documentation, and MCP tool integrations that make it easy to build autonomous trading agents. Visit our developer documentation to get started with agent development.",
      },
    ],
  },
  {
    id: "security",
    title: "Security",
    items: [
      {
        question: "How does ScaleX ensure security?",
        answer:
          "ScaleX employs multiple security layers including audited smart contracts, Chainlink oracle integration for tamper-proof price feeds, isolated risk pools for lending markets, and the X402 protocol for secure agent-to-protocol payments.",
      },
      {
        question: "What is the X402 protocol?",
        answer:
          "X402 is a payment protocol that enables secure, verifiable transactions between AI agents and services. It provides cryptographic proof of payment and service delivery, ensuring neither party can be defrauded in agent-to-protocol interactions.",
      },
      {
        question: "Are smart contracts audited?",
        answer:
          "ScaleX's smart contracts undergo rigorous security audits by reputable firms. We also maintain a bug bounty program to incentivize responsible disclosure of any vulnerabilities. All audit reports are publicly available in our documentation.",
      },
    ],
  },
  {
    id: "technical",
    title: "Technical",
    items: [
      {
        question: "Which chains does ScaleX support?",
        answer:
          "ScaleX is deployed on Base Sepolia testnet and is designed for multi-chain deployment. The protocol leverages Chainlink CRE (Chainlink Runtime Environment) for cross-chain interoperability and reliable price feeds.",
      },
      {
        question: "What is Chainlink CRE?",
        answer:
          "Chainlink CRE (Chainlink Runtime Environment) is the infrastructure ScaleX uses for reliable oracle feeds, cross-chain messaging, and verifiable computation. It powers price feeds, prediction market resolution, and cross-chain asset transfers.",
      },
      {
        question: "What are the fees on ScaleX?",
        answer:
          "ScaleX charges competitive trading fees that are significantly lower than centralized alternatives. A portion of fees goes to liquidity providers and sxToken holders, aligning incentives across the ecosystem. Detailed fee schedules are available in our documentation.",
      },
    ],
  },
]
